query pageQuery {
  ...LayoutQueryFragment
}

query blogPageQuery {
  ...LayoutQueryFragment
  blogConnection(first: 100) {
    edges {
      node {
        id
        title
        date
        date
        _sys {
          filename
        }
      }
    }
  }
}

query blogQuery($relativePath: String!) {
  ...LayoutQueryFragment
  blog(relativePath: $relativePath) {
    ...BlogParts
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}
